name: COMPILE

on:
  push:
    branches:
      - master
    paths:
      - '**/*.ipynb'
  pull_request:
    branches: [ master ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Check out
      uses: actions/checkout@v1

    - name: Compile and Run the pipeline
      uses: chanwit/action-eksctl-kale@v2
      with:
        region: us-east-1
        cluster: minikube
        awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
        awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        notebook: titanic_ml_comparison.ipynb
