name: Execute notebook

on:
  push:
    branches:
      - master
    paths:
      - '**/*.ipynb'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
    - uses: yaananth/run-notebook@v1
      with:
        notebook: "titanic_ml_comparison.ipynb"
        params: "PATHTOPARAMS.json"
        
    - uses: actions/upload-artifact@master
      if: always()
      with:
        name: output

